CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100),
    role VARCHAR(20) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6)
);

CREATE TABLE dashboard (
    dashboard_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dashboard_name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dashboard_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE equipment (
    equipment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_name VARCHAR(255) NOT NULL,
    field VARCHAR(255),
    dashboard_id BIGINT NOT NULL,
    CONSTRAINT fk_equipment_dashboard FOREIGN KEY (dashboard_id) REFERENCES dashboard(dashboard_id),
    CONSTRAINT uk_equipment_dashboard_name UNIQUE (dashboard_id, equipment_name)
);

CREATE TABLE sensor (
    sensor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_name VARCHAR(255) NOT NULL,
    equipment_id BIGINT NOT NULL,
    CONSTRAINT fk_sensor_equipment FOREIGN KEY (equipment_id) REFERENCES equipment(equipment_id),
    CONSTRAINT uk_sensor_equipment_name UNIQUE (equipment_id, sensor_name)
);

CREATE TABLE widgets (
    widget_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dashboard_id BIGINT NOT NULL,
    equipment_id BIGINT,
    sensor_id BIGINT,
    widget_type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    chart_type VARCHAR(50),
    data_type VARCHAR(50),
    unit VARCHAR(50),
    pos_x INTEGER NOT NULL DEFAULT 0,
    pos_y INTEGER NOT NULL DEFAULT 0,
    width INTEGER NOT NULL DEFAULT 1,
    height INTEGER NOT NULL DEFAULT 1,
    config_json TEXT,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_widgets_dashboard FOREIGN KEY (dashboard_id) REFERENCES dashboard(dashboard_id),
    CONSTRAINT fk_widgets_equipment FOREIGN KEY (equipment_id) REFERENCES equipment(equipment_id),
    CONSTRAINT fk_widgets_sensor FOREIGN KEY (sensor_id) REFERENCES sensor(sensor_id)
);

CREATE TABLE sensor_numeric_history (
    sensor_numeric_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_type VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP(6) NOT NULL,
    unit VARCHAR(255),
    numeric_value DOUBLE PRECISION NOT NULL,
    sensor_id BIGINT NOT NULL,
    CONSTRAINT fk_sensor_numeric_history_sensor FOREIGN KEY (sensor_id) REFERENCES sensor(sensor_id)
);

CREATE TABLE sensor_string_history (
    sensor_string_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP(6) NOT NULL,
    sensor_id BIGINT NOT NULL,
    CONSTRAINT fk_sensor_string_history_sensor FOREIGN KEY (sensor_id) REFERENCES sensor(sensor_id)
);

CREATE TABLE refresh_tokens (
    token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token TEXT NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    is_revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE audit_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    action_type VARCHAR(50) NOT NULL,
    entity_type VARCHAR(50),
    entity_id BIGINT,
    description TEXT,
    request_url VARCHAR(255),
    ip_address VARCHAR(45),
    status VARCHAR(20),
    error_message TEXT,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX idx_dashboard_user_id ON dashboard(user_id);
CREATE INDEX idx_sensor_equipment_id ON sensor(equipment_id);
CREATE INDEX idx_widgets_dashboard_id ON widgets(dashboard_id);
CREATE INDEX idx_widgets_equipment_id ON widgets(equipment_id);
CREATE INDEX idx_widgets_sensor_id ON widgets(sensor_id);
CREATE INDEX idx_sensor_numeric_history_sensor_id_timestamp ON sensor_numeric_history(sensor_id, timestamp DESC);
CREATE INDEX idx_sensor_string_history_sensor_id_timestamp ON sensor_string_history(sensor_id, timestamp DESC);
CREATE INDEX idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at);
CREATE INDEX idx_audit_logs_action ON audit_logs(action_type);
